version: "3.8"

services:
  mongodb:
    restart: always
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - $PWD/db:/data/db
      - $PWD/config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    deploy:
      resources:
        limits:
          memory: 0.5GB
    networks:
      - global_network
